(define (insertion-sort vec)
  (let ((len (vector-length vec)))
    (let outer-loop ((j 1))
        (if (< j len)
            (let ((key (vector-ref vec j)))
              (let inner-loop ((i (- j 1)))
                (if (or (< i 0) (< (vector-ref vec i) key))
                    (begin (vector-set! vec (+ i 1) key)
                           (outer-loop (+ j 1)))
                    (begin (vector-set! vec (+ i 1) (vector-ref vec i))
                           (inner-loop (- i 1))))))
            vec))))