(define (sums-to S x)
  (let ((len (vector-length S)))
    (let loop ((a 0) (b 1))
      (if (< a len)
          (if (< b len)
              (if (= x (+ (vector-ref S a) (vector-ref S b)))
                  (list a b)
                  (loop a (+ b 1)))
              (loop (+ a 1) (+ a 2)))
          '()))))